# Generated by Django 4.0.6 on 2022-08-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
